#auth_verbose = yes
auth_mechanisms = plain login

service auth {
  extra_groups = mail

  unix_listener auth-client {
    group = mail
    mode = 0660
    user = dovecot
  }
  user = dovecot
}

!include auth-passwdfile.conf.ext