listen = *
#first_valid_uid = 97
first_valid_gid = 971

protocol sieve {
}

service managesieve-login {
  inet_listener sieve {
    port = 4190
  }
}

service managesieve {
  process_limit = 1024
}

protocol lda {
  mail_plugins {
    sieve = yes
  }
}

protocol lmtp {
  mail_plugins {
    sieve = yes
  }
}

mail_plugins {
  quota = yes
}

quota User {
}