listen = *
protocols = $protocols pop3 sieve

service imap-login {
  inet_listener imap {
  }
  inet_listener imaps {
  }
}

service pop3-login {
  inet_listener pop3 {
  }
  inet_listener pop3s {
  }
}


service imap {
}

service pop3 {
}

service auth {
  extra_groups = mail

  unix_listener auth-client {
    group = mail
    mode = 0660
    user = dovecot
  }
  user = dovecot
}
#first_valid_uid = 97
first_valid_gid = 971

service managesieve-login {
  inet_listener sieve {
    port = 4190
  }
}

service managesieve {
  process_limit = 1024
}

protocol lda {
  mail_plugins {
    sieve = yes
  }
}

protocol lmtp {
  mail_plugins {
    sieve = yes
  }
}

mail_plugins {
  quota = yes
}

protocol imap {
  mail_plugins {
    imap_quota = yes
  }
}

quota User {
}